Task 1 updates

diff --git a/module2_task0/Makefile b/module2_task0/Makefile
--- a/module2_task0/Makefile
+++ b/module2_task0/Makefile
@@ -9,7 +9,10 @@ build: ## Compiles the source code of the application to a binary named awesome-
 	go build -o awesome-api main.go
 
 run: ## Runs the application in background by executing the binary awesome-api, and write logs into a file named awesome.log.
-	./awesome-api &> awesome.log &
+	chmod u+x ./awesome-api
+	chmod u+x ./awesome.log
+	./awesome-api >./awesome.log 2>&1 &
+	disown
 
 stop: ## Stops the application.
 	kill "$(pgrep awesome-api)"
@@ -18,6 +21,15 @@ clean: ## Delete the binary awesome-api and the log file awesome-api.log.
 	rm -r awesome-api
 	rm awesome-api.log
 
-test: ## Test it to ensure that it behaves as expected.
+test: ## Tests application to ensure that it behaves as expected.
+	if pgrep -x awesome-api > /dev/null
+		then
+  		# The application is running, run make test
+  		./awesome-api >./awesome.log 2>&1 &
+  		exit 0
+	else
+  	# The application is not running, exit with failure code
+  	exit 1
+	fi
 	curl http://localhost:9999
 	curl http://localhost:9999/health
